src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
#[Gedmo\SoftDeleteable(fieldName: 'deletedAt', timeAware: false, hardDelete: true)]
class Task
{
    use TimestampableEntity;    // Adds createdAt and updatedAt fields
    use SoftDeleteableEntity;   // Adds deletedAt field for soft delete

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: 'Please enter a title')]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Assert\NotBlank(message: 'Please enter a description')]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $due_date = null;

    #[ORM\Column]
    private ?bool $is_completed = null;

    #[ORM\Column]
    private ?int $progress = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TaskList $task_list = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(?\DateTimeInterface $due_date): static
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function isCompleted(): ?bool
    {
        return $this->is_completed;
    }

    public function setCompleted(bool $is_completed): static
    {
        $this->is_completed = $is_completed;

        return $this;
    }

    public function getProgress(): ?int
    {
        return $this->progress;
    }

    public function setProgress(int $progress): static
    {
        $this->progress = $progress;

        return $this;
    }

    public function getTaskList(): ?TaskList
    {
        return $this->task_list;
    }

    public function setTaskList(?TaskList $task_list): static
    {
        $this->task_list = $task_list;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\User;
use App\Entity\TaskList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TaskType extends AbstractType
{
    // Build the form with the specified fields and their options
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // Add title field
            ->add('title', TextType::class, [
                'required' => true,             // Field is mandatory
                'empty_data' => '',             // Default value if the field is empty
                'label_attr' => [
                    'class' => 'form-label',    // CSS class for the label
                    'for' => 'name',            // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'class' => 'form-control',  // CSS class for the input
                    'id' => 'name',             // HTML 'id' attribute for the input
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        // Custom error message if field is empty
                        'message' => 'Please enter a title',
                    ]),
                ],
            ])
            ->add('description', TextareaType::class, [
                'required' => true,             // Field is mandatory
                'empty_data' => '',             // Default value if the field is empty
                'label_attr' => [
                    'class' => 'form-label',    // CSS class for the label
                    'for' => 'description',     // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'class' => 'form-control',  // CSS class for the input
                    'id' => 'description',      // HTML 'id' attribute for the input
                ],
                'constraints' => [
                    new Assert\NotBlank([
                        // Custom error message if field is empty
                        'message' => 'please enter a description',
                    ]),
                ],
            ])
            // Add due_date field
            ->add('due_date', DateType::class, [
                'widget' => 'choice',           // Render date as dropdowns for day, month, and year
                'placeholder' => '',            // Placeholder text for the dropdowns
                'required' => false,            // Field is optional
                'label_attr' => [
                    'class' => 'form-label',    // CSS class for the label
                    'for' => 'due_date',        // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'id' => 'due_date',         // HTML 'id' attribute for the input
                ],
            ])
            // Add progress field
            ->add('progress', RangeType::class, [
                'label_attr' => [
                    'class' => 'form-label',    // CSS class for the label
                    'for' => 'progress',        // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'class' => 'form-range',    // CSS class for the range input
                    'id' => 'progress',         // HTML 'id' attribute for the range input
                    'min' => 0,                 // Minimum value for the range
                    'max' => 100,               // Maximum value for the range
                    'step' => 1,                // Step value for the range
                    // JavaScript event handler for updating range value
                    'oninput' => 'updateRangeValue(this.value)',
                ],
            ])
            // Add user field
            ->add('user', EntityType::class, [
                'class' => User::class,         // Entity class to use for the choices
                'choice_label' => function (User $user) {
                    // Display user names
                    return $user->getFirstname() . ' ' . $user->getLastname();
                },
                'placeholder' => '',            // Placeholder text for the select input
                'required' => false,            // Field is optional
                'label_attr' => [
                    'class' => 'form-label',    // CSS class for the label
                    'for' => 'user',            // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'id' => 'user',             // HTML 'id' attribute for the select input
                ],
            ])
            // Add chooseTask field
            ->add('chooseTask', CheckboxType::class, [
                'mapped' => false,                  // Field is not mapped to the entity
                'required' => false,                // Field is optional
                'label'    => 'Choose the task ?',  // Label text
                'label_attr' => [
                    'class' => 'form-check-label',  // CSS class for the label
                    'for' => 'flexSwitchCheck',     // HTML 'for' attribute for the label
                ],
                'attr' => [
                    'class' => 'form-check-input',  // CSS class for the checkbox
                    'id' => 'flexSwitchCheck',      // HTML 'id' attribute for the checkbox
                ]
            ]);
    }

    // Configure options for this form type
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,    // Associate form with the Task entity
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Entity\TaskList;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

// Restrict access to users with the 'ROLE_ADMIN' role
#[IsGranted('ROLE_ADMIN')]
// Define the base route for all task-related actions under 'admin/task'
#[Route('admin/task')]
class TaskController extends AbstractController
{
    // Route to display all tasks
    #[Route('/', name: 'app_task_index', methods: ['GET'])]
    public function index(Request $request, TaskRepository $taskRepository): Response
    {
        $page = $request->query->getInt('page', 1); // Current page, by default 1
        $limit = 10; // Number of tasks per page

        // Retrieve sort settings
        $sortField = $request->query->get('sort', 'id'); // Default sort by ID
        $sortOrder = $request->query->get('order', 'asc'); // Default ascending order

        // Using the repository method to retrieve users with paging and sorting
        $pagination = $taskRepository->findPaginatedTasks($page, $limit, $sortField, $sortOrder);

        return $this->render('task/index.html.twig', [
            'pagination' => $pagination,
            'sortField' => $sortField,
            'sortOrder' => $sortOrder,
        ]);
    }

    // Route to create a new task for a specific task list
    #[Route('admin/task_list/{id}/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, TaskList $taskList): Response
    {
        // Create a new Task entity
        $task = new Task();
        // Create and handle the form for creating a new task
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);
        
        // Check if the form is submitted and valid
        if ($form->isSubmitted() && $form->isValid()) {
            // Set the initial state of the task (not completed) and associate it with a task list
            $task->setCompleted(false);
            $task->setTaskList($taskList);

            // Persist the task entity and flush changes to the database
            $entityManager->persist($task);
            $entityManager->flush();

            // Redirect to the task list show page after saving
            return $this->redirectToRoute('app_task_list_show', ['id' => $taskList->getId()], Response::HTTP_SEE_OTHER);
        }

        // Render the form for creating a new task
        return $this->render('task/new.html.twig', [
            'task' => $task,
            'task_list' => $taskList,
            'form' => $form,
        ]);
    }

    // Route to display a specific task
    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        // Render the task details page
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    // Route to edit an existing task
    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        // Create and handle the form for editing a task
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        // Check if the form is submitted and valid
        if ($form->isSubmitted() && $form->isValid()) {
            // Get the progress of the task from the form data
            $progress = $form->get('progress')->getData();

            // If the task progress reaches 100%, mark it as completed
            if ($progress == 100) {
                $task->setCompleted(true);
                $entityManager->persist($task);
            }

            // Save changes to the database
            $entityManager->flush();

            // Redirect to the task show page after editing
            return $this->redirectToRoute('app_task_show', ['id' => $task->getId()], Response::HTTP_SEE_OTHER);
        }

        // Render the form for editing a task
        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    // Route to delete a specific task
    #[Route('/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        // Verify the CSRF token to ensure the deletion request is legitimate
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->getPayload()->getString('_token'))) {
            // Remove the task entity and flush changes to the database
            $entityManager->remove($task);
            $entityManager->flush();
        }

        // Redirect to the task index page after deletion
        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">

    {#  Hidden field containing the CSRF token to secure the delete request.
        The token is generated based on the user's ID. #}
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">

    {#  Delete button with a Bootstrap class for a "danger" style button.
        When clicked, a confirmation dialog will appear. #}
    <button class="btn btn-danger">Delete</button>
</form>

templates/task/edit.html.twig
{% extends 'base.html.twig' %}
{# This template extends the base layout. #}

{% block title %}Edit Task{% endblock %}
{# Sets the page title to "Edit Task". #}

{% block body %}
    <div class=" d-flex flex-column vh-100 justify-content-center  align-items-center">
        <div class="w-25 border border-1 border-dark p-5 rounded bg-secondary text-white">

            <h1 class="text-center">Edit Task</h1>

            {# Start the form with 'novalidate' attribute to handle validation manually #}
            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            <div class="d-grid gap-3">

                {# Render label and input for 'tittle' field, pre-filling with current task data #}
                <div>
                    {{ form_label(form.title) }}
                    {{ form_errors(form.title) }}
                    {{ form_widget(form.title, { 'attr': {'value': task.title} }) }}
                </div>

                {# Render label and input for 'description' field, pre-filling with current task data #}
                <div>
                    {{ form_label(form.description) }}
                    {{ form_errors(form.description) }}
                    {{ form_widget(form.description, { 'attr': {'value': task.description} }) }}
                </div>

                {# Render label and input for 'due_date' field, pre-filling with current task data #}
                <div>
                    {{ form_label(form.due_date) }}
                    {{ form_widget(form.due_date, { 'attr': {'value': task.dueDate ? task.dueDate|date('Y-m-d') : ''} }) }}
                </div>

                <div class="mb-3 position-relative">
                    {# Render the label for the 'progress' field #}
                    {{ form_label(form.progress) }}

                    {# Render the widget for the 'progress' field with the current value #}
                    <div class="d-flex align-items-center">
                        {# Display the current value of the 'progress' field as a percentage #}
                        {{ form_widget(form.progress, { 'attr': {'value': task.progress} }) }}
                        <span id="rangeValue" class="position-absolute border border-2 border-secondary rounded-3 pb-1 bg-white text-dark text-center">{{ form.vars.value.progress }} %</span>
                    </div>
                </div>

                {# Render the label for the 'user' field and display the assigned user, if there is one #}
                <div class="mt-3">
                    {{ form_label(form.user) }} <span> Assigned </span>
                    {{ form_widget(form.user, { 'attr': {'value': task.user ? task.user.getFirstname() ~ ' ' ~ task.user.getLastname() : ''} }) }}
                </div>

                {# Conditional display of the 'chooseTask' field based on user roles #}
                {% if is_granted('ROLE_ADMIN') %}

                    {# Hide the 'chooseTask' field widget and its label #}
                    <div class="form-check form-switch d-none">
                        {{ form_widget(form.chooseTask) }}
                        {{ form_label(form.chooseTask, null) }}
                    </div>
                {% elseif is_granted('ROLE_USER') %}
                
                    {# Render the 'chooseTask' field widget and its label #}
                    <div class="form-check form-switch">
                        {{ form_widget(form.chooseTask) }}
                        {{ form_label(form.chooseTask, null) }}
                    </div>
                {% endif %}

                <div class="d-flex justify-content-end">
                    {# Include a form template for submit button with custom label #}
                    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}
                </div>
            </div>
            {{ form_end(form) }}

            <div class="row mt-3">
                <div class="col">
                    {# Link to go back to the list of tasks #}
                    <a class="btn btn-dark" href="{{ path('app_task_index') }}">back to list</a>
                </div>
                <div class="col-3">
                    {# Include the delete form template #}
                    {{ include('task/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}
{# This template extends the base layout. #}

{% block title %}Task index{% endblock %}
{# Sets the page title to "Task index". #}

{% block body %}
    {#  Display flash messages, which may include status alerts or notifications. 
        These are rendered as Bootstrap alerts. #}
    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endfor %}

    <h1 class="text-center">Task index</h1>

    {# Table to display task data in a dark Bootstrap-styled table with hover effects. #}
    <table class="table table-dark table-hover">
        <thead>
            <tr class="text-center">
                <th class="text-start">
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'id', 'order': sortField == 'id' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'id' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        ID
                    </a>
                </th>
                <th class="text-start">
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'title', 'order': sortField == 'title' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'title' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Title
                    </a>
                </th>
                <th class="text-start">Description</th>
                <th>
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'due_date', 'order': sortField == 'due_date' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'due_date' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Due Date
                    </a>
                </th>
                <th>
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'is_completed', 'order': sortField == 'is_completed' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'is_completed' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Is Completed
                    </a>
                </th>
                <th>
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'progress', 'order': sortField == 'progress' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'progress' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Progress
                    </a>
                </th>
                <th>
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'createdAt', 'order': sortField == 'createdAt' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'createdAt' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Created At
                    </a>
                </th>
                <th>
                    <a href="{{ path('app_task_index', app.request.query.all | merge({'sort': 'updatedAt', 'order': sortField == 'updatedAt' and sortOrder == 'asc' ? 'desc' : 'asc'})) }}"
                    class="sort-link {% if sortField == 'updatedAt' %}{{ sortOrder == 'asc' ? 'asc' : 'desc' }}{% endif %}">
                        Updated At
                    </a>
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {# Loop through the 'pagination' variable to display each task in a table row #}
        {% for task in pagination %}
            <tr class="text-center">
                {# Display individual task details like ID, title, description, etc. #}
                <td class="text-start">{{ task.id }}</td>
                <td class="text-start">{{ task.title }}</td>
                <td class="text-start">{{ task.description }}</td>
                <td>{{ task.dueDate ? task.dueDate|date('Y-m-d') : '' }}</td>
                <td>{{ task.isCompleted ? 'Yes' : 'No' }}</td>
                <td>
                    <div class="progress" style="height: 25px;" title="{{ task.progress }}%">
                        <div class="progress-bar bg-success" role="progressbar" style="width: {{ task.progress }}%;" aria-valuenow="{{ task.progress }}" aria-valuemin="0" aria-valuemax="100">
                            {{ task.progress }}%
                        </div>
                    </div>
                </td>
                <td>{{ task.createdAt ? task.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ task.updatedAt ? task.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    {#  Display action buttons to show, edit. #}
                    <a class="btn btn-primary" href="{{ path('app_task_show', {'id': task.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            {# If no tasks are found, display a row with a message saying no records are available. #}
            <tr>
                <td colspan="9"  class="text-center">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if pagination.count > 10 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if pagination.hasPreviousPage() %}
                <!-- Show the "Previous" button if there is a previous page -->
                <li class="page-item">
                    <a class="page-link" href="{{ path('app_task_index', app.request.query.all | merge({'page': pagination.previousPage})) }}" aria-label="Précédent">
                        <span aria-hidden="true">&laquo; Previous</span> <!-- Left double arrow for "Previous" -->
                    </a>
                </li>
            {% endif %}

            <!-- Loop through all the pages -->
            {% for page in 1..pagination.nbPages %}
                <li class="page-item{% if page == pagination.currentPage %} active{% endif %}">
                    <!-- Highlight the current page by adding the 'active' class -->
                    <a class="page-link" href="{{ path('app_task_index', app.request.query.all | merge({'page': page})) }}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if pagination.hasNextPage() %}
                <!-- Show the "Next" button if there is a next page -->
                <li class="page-item">
                    <a class="page-link" href="{{ path('app_task_index', app.request.query.all | merge({'page': pagination.nextPage})) }}" aria-label="Suivant">
                        <span aria-hidden="true">Next &raquo;</span> <!-- Right double arrow for "Next" -->
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}
{# This template extends the base layout. #}

{% block title %}Task Info{% endblock %}
{# Sets the page title to "Task Info". #}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-auto">

            <h1 class="text-center">Task info</h1>

            {# Card containing the task's information table #}
            <div class="card p-3">
                <div class="card-body">
                    <div class="row w-100">
                        {# Display the task's ID #}
                        <h5 class="col-auto card-title">Id : {{ task.id }}</h5>
                        {# Display the task's title #}
                        <h5 class="col text-center card-title">{{ task.title }}</h5>
                    </div>
                    {# Display the task's description #}
                    <h6 class="card-title mt-4">Description :</h6>
                    <p class="card-text">{{ task.description }}</p>

                    {# Display the creation date of the task in the specified format #}
                    <p class="fst-italic custom-small-text m-0"><b>Created at :</b> {{ task.createdAt ? task.createdAt|date('Y-m-d H:i:s') : '' }}</p>

                    {# Display the last updated date of the task #}
                    <p class="fst-italic custom-small-text m-0"><b>Updated at :</b> {{ task.updatedAt ? task.updatedAt|date('Y-m-d H:i:s') : '' }}</p>
                </div>

                {# Table to display task data in a white Bootstrap-styled table with hover effects. #}
                <table class="table table-white table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>Due_date</th>
                            <th>Is_completed</th>
                            <th>Progress</th>
                            <th class="text-start">Assigned to</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="text-center">
                            {# Display the due date or not of the task #}
                            <td>{{ task.dueDate ? task.dueDate|date('Y-m-d') : '' }}</td>

                            {# Display the 'is completed' boolean of the task #}
                            <td>{{ task.isCompleted ? 'Yes' : 'No' }}</td>
                            
                            <td>
                                {# Progress bar container with a dark border and fixed height #}
                                <div class="progress border border-dark" style="height: 25px;" title="{{ task.progress }}%">

                                    {# The progress bar itself, showing the task's progress percentage #}
                                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ task.progress }}%;" aria-valuenow="{{ task.progress }}" aria-valuemin="0" aria-valuemax="100">
                                        
                                        {# Display the progress percentage inside the progress bar #}
                                        {{ task.progress }}%
                                    </div>
                                </div>
                            </td>

                            {# Display or not, the firstname and lastname of the assigned user #}
                            {% if (task.user == null) %}
                                <td></td>
                            {% else %}
                                <td class="text-start">{{ task.user.firstname }} {{ task.user.lastname }}</td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>

                {# Buttons section to return to the task_list or edit the task details #}
                <div class="d-flex gap-2">
                    <div class="btn-group w-100" role="group" aria-label="Basic example">
                        <a class="btn btn-dark" href="{{ path('app_task_list_show', { 'id': task.taskList.id }) }}">back to task list</a>
                        <a class="btn btn-secondary" href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>
                    </div>

                    {# Include the delete form for the task, which will render a button to delete the task #}
                    <div>
                        {{ include('task/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}